### ISSUE TITLE
Provide HW for the performance testing

### ISSUE THREAD

**Issue by dejanpan** [ros-realtime/community#3]
1. [x] Andrei to try to do it via Baylibre
1. [ ] ~~JSpeed to try to do it via ADLINK~~
1. [x] Check this internally

Additional requirements:
1. 2 affordable embedded board as a reference HW for the performance testing: Intel UP2 and ARM Raspberry Pi4.
1. We can build the performance test software on the Open Robotics premises but would like to deploy and run it on the real HW.
1. install two boards and provide an access to these boards remotely (power on/off, deploy images and tests, retrieve test results) by the ROS2 RTWG team.

**Comment by dejanpan** [comment]
ADLINK example boards:

1. https://www.adlinktech.com/en/ROS2-Solution
2. https://www.adlinktech.com/Products/Industrial_PCs_Fanless_Embedded_PCs/IntegratedFanlessEmbeddedComputers/MXE-5600_Series?lang=en 
3. https://www.ipi.wiki

**Comment by y-okumura-isp** [comment]
We plan to set up RPi4 but it seems to take a time (we start from purchasning).
So We have updated our RP3B+ setup manual.
It is for RPi3, but we hope we can consider what to write for RPi4 manual.
https://github.com/hsgwa/ros2_timer_latency_measurement/blob/master/setup.foxy.md

We've find out the followings:

- First, we get and build the foxy 1.0.0 to build the exactly same code(https://github.com/ros2/ros2/archive/release-foxy-20200605.zip)
- Second, we run pendulum_demo (That's just for starters).
  - We want to verify minimum behavior: cyclictest for OS,  pendulum for ROS2
- Third, we try to build buildfarm_perf_tests but we cannot because of insufficient memory.
  - In PC, we use about 3 GB to build, or 1 GB to run buildfarm_perf_tests.
  - Considering the operating system and some margin, we'll need **4 GB to build, or 2 GB to run**.

To reproduce our discourse posts, you can use following tools if you hope.
- https://github.com/hsgwa/ros2_timer_latency_measurement.
- https://github.com/y-okumura-isp/TwoWaysMeasurement

**Comment by dejanpan** [comment]
Joe Update:
1. Mid Dec 2020 the space will be available
1. HW: IAC AD system, ROSCube, Arm-nased NXP IMX8M+

**Comment by y-okumura-isp** [comment]
Publishing frequency looks to drop on ARM.

- https://github.com/ros2/rclcpp/issues/1431
  - first reporter says: set 200KB 10Hz => 6 Hz on ARM platform. DDS is FastRTPS.
  - What I reproduces: 
    - 700 Mbps is the maximum performance when we use RPi4, loopback.
    - 8 MB x 10 Hz => aobut 9.6 Hz on RPi4. FastRTPS & CycloneDDS. (640 Mbps)
    - resources such as CPU/memory are idle
    - CycloneDDS can 10 Hz by setting kernel parameter.
- https://github.com/ros2/rclcpp/issues/1485
  - 200KB 10 Hz => 1 Hz when we use CycloneDDS and 1 publisher and 2 subscribers on RPi4.

As we consider RPi4 and NXP IMX8M+ above, I shared it.

**Comment by carlossvg** [comment]
From Andrei. Hosting in Baylibre cost money and we decided to host it with Adlink. 

@joespeed Any progress on this topic?

**Comment by carlossvg** [comment]
After an internal sync we decided not to provide any real-time buildfarm for the moment.
